// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf module-codegen`

export interface Result {
    /** Whether the share was successful */
    success: boolean;
    /** Error message if failed */
    error?: string;
}
export interface UniqueId {
    /** Unique id */
    id: string;
}
export interface InviteCode {
    /** Invite code */
    code: string;
}

export {};