// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `webf module-codegen`

export interface Result {
    /** Whether the share was successful */
    success: boolean;
    /** Error message if failed */
    error?: string;
}
export interface UniqueId {
    /** Unique id */
    id: string;
}
export interface InviteCode {
    /** Invite code */
    code: string;
}
export interface ToastMessage {
    /** Toast message content */
    message: string;
}
export /**
 * Points page navigation target
 * @description Navigation targets for points reward actions
 *
 * - `cryptoList` - Navigate to Crypto list page (for "Get 100 points" and "Trade crypto")
 * - `earn` - Navigate to Earn page (for "Keep $1,000+ in Earn")
 * - `addMoney` - Navigate to Add Money page (for "Keep $1,000+ in WLFI balance")
 */
type PointNavigationTarget = 'cryptoList' | 'earn' | 'addMoney';
export interface NavigationParams {
    /** Target page to navigate to */
    target: PointNavigationTarget;
}
export interface ClipboardText {
    /** Text content from clipboard, null if empty or unavailable */
    text: string | null;
}

export {};